### ISSUE TITLE
new zola attrbutes

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/www_examplezola#4]
create new attribute for the new zola 

for paragraphs, indentation left, 

for paragraphs, indentation right

for section or row to have zero / no margin and no padding

**Comment by ehab-hassan** [comment]
Is that what u need?I tested it at io for now if ok ll apply at example Zola
![cefd6722-a7f9-498d-ab0b-4bc3953ba33c](https://user-images.githubusercontent.com/10484295/230886885-8e7b1b7b-e7be-4143-b78e-fdb612b5c87a.png)

**Comment by sasha-astiadi** [comment]
if the image is on the right, the text is on the right please @ehab-hassan , the first one is good

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/231426612-9db66ca2-18b5-448b-95b8-dc9e9cb49af2.png)

if u need to add right text alignment but right
{% row(style="right between mbottom") %}

if u need left ( default ) dont write anything
{% row(style="between mbottom") %}

**Comment by sasha-astiadi** [comment]
@ehab-hassan can we already do this on tf.io? thank you ehaB!

**Comment by ehab-hassan** [comment]
![test](https://user-images.githubusercontent.com/10484295/231443916-07f3ceec-a2f6-48fa-8d89-1cbfc08c1614.png)

done at examplezola and io

**Comment by sasha-astiadi** [comment]
thank you ehab
